# Generated by Django 3.1 on 2020-08-25 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True, verbose_name='Key')),
                ('file', models.FileField(max_length=512, upload_to='tables/pdv_red/', verbose_name='File')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 24, 22, 44, 56, 944127), verbose_name='Emission Dateo')),
                ('status', models.CharField(choices=[('F', 'Finished'), ('R', 'Running'), ('E', 'Error')], default='C', help_text='Concluído/Em andamento/Erro', max_length=1, verbose_name='Status de processamento')),
                ('exception', models.TextField(blank=True, max_length=512, null=True, verbose_name='Excessões')),
                ('exceptions_file', models.FileField(max_length=512, null=True, upload_to='tables/pdv_red/', verbose_name='Arquivo de exceções')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=588, null=True, verbose_name='Hostname')),
                ('ip_adress', models.CharField(blank=True, max_length=588, null=True, verbose_name='Ip Adress')),
                ('vulnerability', models.ManyToManyField(blank=True, null=True, to='vulnerabilities.Vulnerability')),
            ],
        ),
    ]
