# Generated by Django 3.1 on 2020-08-25 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20200824_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 23, 3, 42, 750345), verbose_name='Emission Dateo'),
        ),
    ]
