# Generated by Django 3.1 on 2020-08-25 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20200824_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostsfiles',
            options={'verbose_name': 'hosts files', 'verbose_name_plural': '2. Hosts Files'},
        ),
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 12, 48, 57, 189141), verbose_name='Emission Date'),
        ),
        migrations.AlterField(
            model_name='hostsfiles',
            name='exception',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Exceptions'),
        ),
        migrations.AlterField(
            model_name='hostsfiles',
            name='exceptions_file',
            field=models.FileField(max_length=512, null=True, upload_to='files', verbose_name='Exceptions File'),
        ),
        migrations.AlterField(
            model_name='hostsfiles',
            name='file',
            field=models.FileField(max_length=512, upload_to='files', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='hostsfiles',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('R', 'Running'), ('E', 'Error')], default='F', help_text='Finished/Running/Error', max_length=1, verbose_name='Process Status'),
        ),
    ]
