# Generated by Django 3.1 on 2020-08-25 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20200825_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'hosts', 'verbose_name_plural': '1. Hosts'},
        ),
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 13, 54, 35, 85626), verbose_name='Emission Date'),
        ),
    ]
