# Generated by Django 3.1 on 2020-08-25 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_auto_20200825_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 13, 56, 12, 853684), verbose_name='Emission Date'),
        ),
    ]
