# Generated by Django 3.1 on 2020-08-25 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0007_auto_20200825_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 14, 18, 56, 694843), verbose_name='Emission Date'),
        ),
    ]
