# Generated by Django 3.1 on 2020-08-30 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0006_auto_20200825_1419'),
        ('hosts', '0011_auto_20200828_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='vulnerabilities',
            field=models.ManyToManyField(blank=True, to='vulnerabilities.Vulnerability'),
        ),
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 11, 58, 35, 770771), verbose_name='Emission Date'),
        ),
    ]
