# Generated by Django 3.1 on 2020-08-30 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_auto_20200830_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 15, 32, 59, 19512), verbose_name='Emission Date'),
        ),
    ]
