# Generated by Django 3.1 on 2020-08-30 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0015_auto_20200830_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 18, 57, 0, 557835), verbose_name='Emission Date'),
        ),
    ]
