# Generated by Django 3.1 on 2020-08-30 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0017_auto_20200830_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 19, 0, 41, 949703), verbose_name='Emission Date'),
        ),
    ]
