# Generated by Django 3.1 on 2020-08-31 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0020_auto_20200831_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 15, 32, 36, 277019), verbose_name='Emission Date'),
        ),
    ]
