# Generated by Django 3.1 on 2020-08-31 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0021_auto_20200831_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 21, 49, 15, 76837), verbose_name='Emission Date'),
        ),
    ]
