# Generated by Django 3.1 on 2020-08-31 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0022_auto_20200831_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsfiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 22, 46, 22, 17044), verbose_name='Emission Date'),
        ),
    ]
