# Generated by Django 3.1 on 2020-08-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=588, null=True, verbose_name='Title')),
                ('severity', models.CharField(blank=True, max_length=588, null=True, verbose_name='Severity')),
                ('cvss', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='CVSS')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('corrected', models.BooleanField(verbose_name='Corrected ?')),
            ],
        ),
    ]
