# Generated by Django 3.1 on 2020-08-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='corrected',
            field=models.BooleanField(blank=True, null=True, verbose_name='Corrected ?'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
    ]
