# Generated by Django 3.1 on 2020-08-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0004_auto_20200825_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='cvss',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='CVSS'),
        ),
    ]
