# Generated by Django 3.1 on 2020-08-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilities', '0005_auto_20200825_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='cvss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CVSS'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication Date'),
        ),
    ]
